// Builds a single, dependency-free crest catalogue for every club referenced
// by game_db.js and euroleague_db.js.  The crests are original initials, not
// official club logos; see the project's legal notice.
import { writeFile } from "node:fs/promises";
import { fileURLToPath, pathToFileURL } from "node:url";
import path from "node:path";

const here = path.dirname(fileURLToPath(import.meta.url));
const { gameDatabase } = await import(pathToFileURL(path.join(here, "../data/game_db.js")).href);
const { euroleagueDatabase } = await import(pathToFileURL(path.join(here, "../data/euroleague_db.js")).href);
const output = path.join(here, "../data/team_crests.js");

const teams = new Map();
for (const source of [gameDatabase, euroleagueDatabase]) for (const team of source.teams) {
  const old = teams.get(team.team_id);
  teams.set(team.team_id, { team_id: team.team_id, canonical_name: team.canonical_name, competitions: [...new Set([...(old?.competitions ?? []), source === gameDatabase ? "winner_league" : "euroleague"])] });
}
const initials = name => name.replace(/\b(?:BC|AS|FC|KK)\b/gi, "").split(/[\s'-]+/).filter(Boolean).slice(0, 3).map(word => word[0]).join("").toUpperCase() || "?";
const hash = value => [...value].reduce((n, char) => (n * 33 + char.charCodeAt(0)) >>> 0, 5381);
const svg = (id, name) => {
  const h = hash(id) % 360, h2 = (h + 42) % 360, text = initials(name);
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 116" role="img" aria-label="${name.replace(/&/g, "&amp;").replace(/"/g, "&quot;")}"><defs><linearGradient id="g" x1="0" y1="0" x2="1" y2="1"><stop stop-color="hsl(${h} 76% 42%)"/><stop offset="1" stop-color="hsl(${h2} 75% 22%)"/></linearGradient></defs><path d="M50 3 94 19v37c0 28-18 47-44 57C24 103 6 84 6 56V19z" fill="url(#g)" stroke="#f7d76a" stroke-width="5"/><path d="M15 24h70" stroke="rgba(255,255,255,.55)" stroke-width="3"/><text x="50" y="70" text-anchor="middle" fill="#fff" font-family="Arial,sans-serif" font-size="${text.length > 2 ? 27 : 37}" font-weight="800">${text}</text></svg>`;
};
const catalogue = Object.fromEntries([...teams.values()].sort((a, b) => a.team_id.localeCompare(b.team_id)).map(team => [team.team_id, { ...team, initials: initials(team.canonical_name), svg: svg(team.team_id, team.canonical_name) }]));
await writeFile(output, `// Generated by game/tools/build_team_crests.mjs. Original initial crests, not official club logos.\nexport const teamCrests = ${JSON.stringify(catalogue)};\nexport const teamCrest = (teamId) => teamCrests[teamId] ?? null;\n`, "utf8");
console.log(`Wrote ${Object.keys(catalogue).length} team crests to ${output}`);
