// Builds a single, dependency-free crest catalogue for every club referenced
// by game_db.js and euroleague_db.js.  The crests are original initials, not
// official club logos; see the project's legal notice.
import { writeFile } from "node:fs/promises";
import { fileURLToPath, pathToFileURL } from "node:url";
import path from "node:path";

const here = path.dirname(fileURLToPath(import.meta.url));
const { gameDatabase } = await import(pathToFileURL(path.join(here, "../data/game_db.js")).href);
const { euroleagueDatabase } = await import(pathToFileURL(path.join(here, "../data/euroleague_db.js")).href);
const output = path.join(here, "../data/team_crests.js");
// the arcade's club colours (traditional colours where known, Hapoel red, Maccabi yellow/blue, else a stable hue)
const { clubColors } = await import(pathToFileURL(path.join(here, "../js/lib/clubs.js")).href);

const teams = new Map();
for (const source of [gameDatabase, euroleagueDatabase]) for (const team of source.teams) {
  const old = teams.get(team.team_id);
  teams.set(team.team_id, { team_id: team.team_id, canonical_name: team.canonical_name, competitions: [...new Set([...(old?.competitions ?? []), source === gameDatabase ? "winner_league" : "euroleague"])] });
}
const initials = name => name.replace(/\b(?:BC|AS|FC|KK)\b/gi, "").split(/[\s'-]+/).filter(Boolean).slice(0, 3).map(word => word[0]).join("").toUpperCase() || "?";
const hash = value => [...value].reduce((n, char) => (n * 33 + char.charCodeAt(0)) >>> 0, 5381);
// light club colours (white, yellow) get dark initials, so the letters always read
const light = (c) => { const m = /^#([0-9a-f]{6})$/i.exec(c); if (!m) return /hsl\(\d+ \d+% (8\d|9\d)%\)/.test(c); const n = parseInt(m[1], 16); return ((n >> 16) * 299 + ((n >> 8) & 255) * 587 + (n & 255) * 114) / 1000 > 160; };
const svg = (id, name) => {
  const [c1, c2] = clubColors(id), text = initials(name), gid = `crest-g-${id}`; // a unique gradient id: many crests share a page
  const ink = light(c1) ? "#111" : "#fff";
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 116" role="img" aria-label="${name.replace(/&/g, "&amp;").replace(/"/g, "&quot;")}"><defs><linearGradient id="${gid}" x1="0" y1="0" x2="0" y2="1"><stop offset=".62" stop-color="${c1}"/><stop offset=".62" stop-color="${c2}"/></linearGradient></defs><path d="M50 3 94 19v37c0 28-18 47-44 57C24 103 6 84 6 56V19z" fill="url(#${gid})" stroke="#f7d76a" stroke-width="5"/><path d="M15 24h70" stroke="${ink === "#fff" ? "rgba(255,255,255,.55)" : "rgba(0,0,0,.35)"}" stroke-width="3"/><text x="50" y="66" text-anchor="middle" fill="${ink}" font-family="Arial,sans-serif" font-size="${text.length > 2 ? 27 : 37}" font-weight="800">${text}</text></svg>`;
};
const catalogue = Object.fromEntries([...teams.values()].sort((a, b) => a.team_id.localeCompare(b.team_id)).map(team => [team.team_id, { ...team, initials: initials(team.canonical_name), svg: svg(team.team_id, team.canonical_name) }]));
await writeFile(output, `// Generated by game/tools/build_team_crests.mjs. Original initial crests, not official club logos.\nexport const teamCrests = ${JSON.stringify(catalogue)};\nexport const teamCrest = (teamId) => teamCrests[teamId] ?? null;\n`, "utf8");
console.log(`Wrote ${Object.keys(catalogue).length} team crests to ${output}`);
