// Club logos. Put logo files in game/crests/ named by team id (maccabi_tel_aviv.webp, hapoel_jerusalem.svg, ...:
// the list is in game/crests/README.md), then run
//   npm run crests:local
// It writes game/crests/manifest.js, and every crest of that club shows the logo. The folder is part of the
// site: committed and published. Clubs without a logo file keep the drawn initials shield (data/team_crests.js).
// Logos are the clubs' trademarks: shown only to identify the team, and removed on request (see the terms page).
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { teamCrests } from "../data/team_crests.js";

const DIR = path.join(path.dirname(fileURLToPath(import.meta.url)), "../crests");
fs.mkdirSync(DIR, { recursive: true });
const EXT = [".svg", ".png", ".webp", ".jpg", ".jpeg"];

// the list of names to use
const ids = Object.values(teamCrests).sort((a, b) => a.canonical_name.localeCompare(b.canonical_name));
fs.writeFileSync(path.join(DIR, "README.md"), `# Club logos

Put a logo file here for any club, named by its team id, then run \`npm run crests:local\`.
Formats: ${EXT.join(", ")}. A square image with a transparent background looks best.
This folder is published with the site (GitHub and the live arcade).

| File name (any of the formats) | Club | Competition |
|---|---|---|
${ids.map((t) => `| \`${t.team_id}.png\` | ${t.canonical_name} | ${t.competitions.map((c) => (c === "winner_league" ? "Winner League" : "EuroLeague")).join(", ")} |`).join("\n")}
`);

const files = {}, unknown = [];
for (const f of fs.readdirSync(DIR)) {
  const ext = path.extname(f).toLowerCase(), id = path.basename(f, path.extname(f));
  if (!EXT.includes(ext)) continue;
  if (!teamCrests[id]) { unknown.push(f); continue; }
  files[id] = `crests/${f}?v=${Math.round(fs.statSync(path.join(DIR, f)).mtimeMs)}`; // a new file shows up right away
}
fs.writeFileSync(path.join(DIR, "manifest.js"), `// Generated by game/tools/build_local_crests.mjs from the files in this folder. Local only (see README.md).
export const crestFiles = ${JSON.stringify(files, null, 1)};
`);
console.log(`${Object.keys(files).length} logos found${unknown.length ? `; not a known team id (rename them): ${unknown.join(", ")}` : ""}.`);
console.log(`Names to use: game/crests/README.md`);
