// Copies the arcade's fonts from the Fontsource packages (SIL Open Font License) into game/fonts and writes
// game/fonts/fonts.css, so pages never load anything from Google's servers (no visitor IPs sent to a third
// party). Only the weights the design uses and the character sets it needs are copied.
//   node game/tools/build_fonts.mjs        (npm run build:fonts)
import { copyFileSync, mkdirSync, readFileSync, writeFileSync, rmSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { join } from "node:path";

const ROOT = fileURLToPath(new URL("../..", import.meta.url));
const OUT = join(ROOT, "game", "fonts");
const FONTS = [
  ["inter", [400, 500, 600, 700, 800], ["latin", "latin-ext"]],
  ["barlow", [400, 500, 600, 700], ["latin", "latin-ext"]],
  ["barlow-condensed", [500, 600, 700, 800], ["latin", "latin-ext"]],
  ["saira-condensed", [600, 700, 800], ["latin", "latin-ext"]],
  ["orbitron", [600, 700, 800], ["latin"]],
  ["heebo", [400, 500, 600, 700, 800, 900], ["hebrew"]], // Hebrew letters only: Latin text keeps the arcade's fonts
];

rmSync(OUT, { recursive: true, force: true });
mkdirSync(OUT, { recursive: true });
let css = "/* Generated by game/tools/build_fonts.mjs from the Fontsource packages (SIL Open Font License 1.1). */\n";
let files = 0;
for (const [name, weights, subsets] of FONTS) {
  const pkg = join(ROOT, "node_modules", "@fontsource", name);
  for (const w of weights) {
    const src = readFileSync(join(pkg, `${w}.css`), "utf8");
    for (const block of src.split(/\n(?=\/\*)/)) {
      const sub = new RegExp(`/\\* ${name}-([a-z-]+)-${w}-normal \\*/`).exec(block)?.[1];
      if (!subsets.includes(sub)) continue;
      const file = /url\(\.\/files\/([^)]+\.woff2)\)/.exec(block)[1];
      copyFileSync(join(pkg, "files", file), join(OUT, file));
      files++;
      css += block.replace(/src: [^;]+;/, `src: url(./${file}) format('woff2');`).trim() + "\n";
    }
  }
}
writeFileSync(join(OUT, "fonts.css"), css);
console.log(`${files} font files, fonts.css written`);
