// Builds game/data/game_db.js: a compact, minified copy of the database with only the
// fields the arcade games use (the full export stays the source of truth).
//   node game/tools/make_game_data.mjs
import { writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { israelBSLDatabase as db } from "../../exports/israel_bsl_2010_2027.js";

const here = dirname(fileURLToPath(import.meta.url));
const STAT_KEYS = ["games", "mpg", "ppg", "rpg", "apg", "spg", "bpg", "fg_pct", "fg3_pct", "ft_pct", "valuation_per_game"];

// most-worn jersey number per player (official rosters), for Guess the Player
const jerseyOf = new Map();
{
  const counts = new Map();
  for (const r of db.player_seasons) {
    if (r.jersey_number === null || r.jersey_number === undefined) continue;
    const m = counts.get(r.player_id) || new Map();
    m.set(r.jersey_number, (m.get(r.jersey_number) || 0) + 1);
    counts.set(r.player_id, m);
  }
  for (const [pid, m] of counts) jerseyOf.set(pid, [...m.entries()].sort((a, b) => b[1] - a[1] || a[0] - b[0])[0][0]);
}

const slim = {
  metadata: { current_season: db.metadata.current_season, season_list: db.metadata.season_list, generated_at: db.metadata.generated_at },
  players: db.players.map((p) => ({
    player_id: p.player_id, name: p.name, birth_date: p.birth_date, nationality: p.nationality,
    nationalities: p.nationalities, height_cm: p.height_cm, primary_position: p.primary_position,
    seasons: p.seasons, teams: p.teams, jersey: jerseyOf.get(p.player_id) ?? null,
  })),
  teams: db.teams.map((t) => ({ team_id: t.team_id, canonical_name: t.canonical_name })),
  seasons: db.seasons.map((s) => ({ season: s.season, status: s.status, teams: s.teams })),
  season_teams: db.season_teams.map((s) => ({ season: s.season, team_id: s.team_id, team_name: s.team_name })),
  player_seasons: db.player_seasons.map((r) => ({
    player_id: r.player_id, season: r.season, team_id: r.team_id, team_name: r.team_name, age: r.age,
    position: r.position, secondary_position: r.secondary_position,
    appeared_in_regular_season: r.appeared_in_regular_season, rating_mock: r.rating_mock,
    stats: r.stats ? Object.fromEntries(STAT_KEYS.map((k) => [k, r.stats[k]])) : null,
  })),
};

const out = join(here, "..", "data", "game_db.js");
mkdirSync(dirname(out), { recursive: true });
writeFileSync(out, "// Generated by game/tools/make_game_data.mjs from exports/israel_bsl_2010_2027.js\n" +
  "export const gameDatabase = " + JSON.stringify(slim) + ";\n");
console.log(`wrote ${out}: ${slim.players.length} players, ${slim.player_seasons.length} player-seasons`);
