// Builds data/national_index.js from data/national_teams_db.js: the national-team facts the app needs up front
// (teams, FIBA zone, and the links between national-team players and Winner League players). The full file
// (about 1 MB) loads only on the national-team pages and in My Career.
// Links: same name (any word order, accents ignored) AND the same birth date when both are known.
// Run: node game/tools/prepare_national.mjs
import fs from "node:fs";
import { nationalTeamsDatabase as N } from "../data/national_teams_db.js";
import { gameDatabase as G } from "../data/game_db.js";

const OUT = new URL("../data/national_index.js", import.meta.url);
const key = (s) => s.normalize("NFD").replace(/[̀-ͯ]/g, "").toLowerCase().replace(/\*/g, "").replace(/[^a-z\s-]/g, " ").replace(/-/g, " ").split(/\s+/).filter(Boolean).sort().join(" ");

// FIBA zone of each team, from the competitions its 2025 rosters came from
const ZONE_OF = (c) => (/EuroBasket|European/.test(c) ? "europe" : /AfroBasket|Africa/.test(c) ? "africa" : /AmeriCup|Americas/.test(c) ? "americas" : /Asia/.test(c) ? "asia" : null);
const zones = {};
for (const r of N.player_seasons) { const z = ZONE_OF(r.competition); if (z) (zones[r.team_id] ||= {})[z] = ((zones[r.team_id] ||= {})[z] || 0) + 1; }
const teams = N.teams.map((t) => {
  const z = Object.entries(zones[t.team_id] || {}).sort((a, b) => b[1] - a[1])[0]?.[0] || null;
  return [t.team_id, t.canonical_name, t.fiba_code, t.world_rank, z];
});

// national-team player <-> Winner League player
const wl = new Map();
for (const p of G.players.filter((x) => x.name)) { const k = key(p.name); if (!wl.has(k)) wl.set(k, []); wl.get(k).push(p); }
const links = [];
let rejected = 0;
const teamOf = new Map(N.player_seasons.map((r) => [r.player_id, r.team_id]));
for (const p of N.players) {
  const cands = wl.get(key(p.name)) || [];
  const same = cands.filter((c) => !c.birth_date || !p.birth_date || c.birth_date === p.birth_date);
  if (cands.length && !same.length) { rejected++; continue; } // same name, different person
  if (same.length !== 1) continue; // none, or ambiguous
  links.push([same[0].player_id, teamOf.get(p.player_id), p.player_id]);
}

const IX = { as_of: N.metadata.as_of, ranking_date: N.metadata.ranking_date, teams, links };
fs.writeFileSync(OUT, `// Generated by game/tools/prepare_national.mjs from national_teams_db.js. Do not edit by hand.
// teams: [team_id, name, FIBA code, world rank, zone]; links: [Winner League player_id, national team_id, national player_id].
export const nationalIndex = ${JSON.stringify(IX)};
`);
console.log(`${teams.length} teams, ${links.length} Winner League links (${rejected} same-name players rejected by birth date)`);
