// Generated by game/tools/build_local_crests.mjs from the logo files in this folder (see README.md).
export const crestFiles = {
 "anadolu_efes": "crests/web/anadolu_efes.webp?v=1791403983000",
 "asvel": "crests/web/asvel.webp?v=1791403986000",
 "baskonia": "crests/web/baskonia.webp?v=1791403985000",
 "bayern_munich": "crests/web/bayern_munich.webp?v=1791403985000",
 "besiktas": "crests/web/besiktas.webp?v=1791403983000",
 "crvena_zvezda": "crests/web/crvena_zvezda.webp?v=1791403984000",
 "dubai_basketball": "crests/web/dubai_basketball.webp?v=1791403984000",
 "fc_barcelona": "crests/web/fc_barcelona.webp?v=1791403984000",
 "fenerbahce": "crests/web/fenerbahce.webp?v=1791403985000",
 "hapoel_tel_aviv": "crests/web/hapoel_tel_aviv.webp?v=1791403985000",
 "maccabi_tel_aviv": "crests/web/maccabi_tel_aviv.webp?v=1791403986000",
 "olimpia_milano": "crests/web/olimpia_milano.webp?v=1791403984000",
 "olympiacos": "crests/web/olympiacos.webp?v=1791403986000",
 "panathinaikos": "crests/web/panathinaikos.webp?v=1791403986000",
 "paris_basketball": "crests/web/paris_basketball.webp?v=1791403987000",
 "partizan": "crests/web/partizan.webp?v=1791403987000",
 "real_madrid": "crests/web/real_madrid.webp?v=1791403987000",
 "valencia_basket": "crests/web/valencia_basket.webp?v=1791403987000",
 "virtus_bologna": "crests/web/virtus_bologna.webp?v=1791403988000",
 "zalgiris_kaunas": "crests/web/zalgiris_kaunas.webp?v=1791403988000"
};
