// Generated by game/tools/build_local_crests.mjs from the logo files in this folder (see README.md).
export const crestFiles = {
 "maccabi_tel_aviv": "crests/maccabi_tel_aviv.webp?v=1791403540338"
};
